### ISSUE TITLE
About Visualization

### ISSUE THREAD

**Issue by StevenZzz07** [diviswen/sanet#1]
Hi, first thanks for your inspiring work! Point cloud rendering figures in your paper are very beautiful, such as the vivid shadows. How do you draw it? Using open3d, meshlab or other programmes?

Thanks!
![image](https://user-images.githubusercontent.com/56421441/110416750-36265700-80cf-11eb-85ff-8f5bbef5c8f2.png)

**Comment by diviswen** [comment]
We first use open3d to create a sphere with norms centered at each point, then use the Keyshot for rendering.

**Comment by StevenZzz07** [comment]
Got it! Thanks a lot!
