### ISSUE TITLE
the version of pytorch

### ISSUE THREAD

**Issue by beibeirory** [diviswen/sanet#2]
Thanks for your code. Could you tell me the version of your pytorch、PyTorch geometric and cuda?

**Comment by diviswen** [comment]
Acutally this code uses Tensorflow instead of Pytorch. The detailed implementations and settings (including tensorflow version) are the same as PointNet++, please see:
https://github.com/charlesq34/pointnet2

**Comment by beibeirory** [comment]
thanks very much.
